<?php
cmd::addcmd('e13,2', '状态');
echo ">> 操作列表";
br();
echo "-";
br();
cmd::addcmd('e13,2', '个人状态');
echo " . ";
cmd::addcmd('e40,2', '随身物品');
br();
cmd::addcmd('e51,2', '好友列表');
echo " . ";
cmd::addcmd('e105', '师徒关系');
br();
cmd::addcmd('e106', '帮派相关');
echo " . ";
cmd::addcmd('e107', '组队相关');
br();
cmd::addcmd('e96', '快捷设置');
echo " . ";
cmd::addcmd('e73', '开关设置');
br();
cmd::addcmd('e108', '任务列表');
echo " . ";
cmd::addcmd('e47,2', '传奇排行');
br();
echo "绿色传奇：仙盟会";
br();
cmd::addcmd('e6', '退出游戏');
echo " . ";
cmd::addcmd('e46', 'GM反馈');
br();
cmd::set_show_return_game(false);
echo "-";
br();
cmd::addcmd('e0', '返回游戏');
